baseURL = 'https://cox96de.github.io'
languageCode = 'en-us'
title = 'Blog website for cox96de'
theme = 'LoveIt'

[params]
defaultTheme = "dark"
title = "Blog website for cox96de"

[params.header]

[params.header.title]
name = "Blog website for cox96de"

[params.app]
title = "Blog website for cox96de"
